### ISSUE TITLE
Incorrect source download link and integration with other COIN-OR projects.

### ISSUE THREAD

**Issue by tkralphs** [conda-forge/coinbonmin-feedstock#18]
### Comment:

I only just now became aware of this feedstock. I am one of the maintainers of Bonmin (and most other COIN-OR projects, although I don't touch Ipopt much). Sources for all COIN-OR projects should now be obtained from Github. Unfortunately, Bonmin has not had a release since we made that switch permanent, so the latest release is still available at https://www.coin-or.org/download/source/Bonmin/. However, future releases (when they come) will only be available on Github. Since the old releases are all already available on Github, it should be safe to switch now.

Any chance we can integrate this feedstock in with the Cbc stack? Mainly, it would be nice to have a consistent naming so that this would become `coin-or-bonmin`. There was also a `coincbc` that we integrated into `coin-or-cbc` here:

https://github.com/conda-forge/coin-or-cbc-feedstock/blob/c013c8d19ff13fc3192a2ee511a58f23b9eaa5f6/recipe/meta.yaml#L65-L74 

What do you think?

**Comment by jschueller** [comment]
ok for changing the name, can you do it ?

**Comment by tkralphs** [comment]
I guess it will be a while if I need to do it and I'm still not fully comfortable with the ins and outs of conda. Maybe @wolfv can help? If not, I may possibly be able to recruit someone. We should eventually also add [Couenne](https://github.com/coin-or/Couenne) and possibly a few other useful projects.

**Comment by jschueller** [comment]
ipopt too I guess
